### ISSUE TITLE
Crash when screen turns on

### ISSUE THREAD

**Issue by jush** [google/physical-web#419]
Every now and then the app crashes when the screen is turned on.
The device is:
 - Nexus 9 running M preview (MPZ44Q)
 - The bluetooth is off all the time
 - This is the crash log

```
--------- beginning of crash
06-22 08:35:04.370  5299  5299 E AndroidRuntime: java.lang.RuntimeException: Error receiving broadcast Intent { act=android.intent.action.SCREEN_ON flg=0x50000010 } in org.physical_web.physicalweb.UriBeaconDiscoveryService$ScreenBroadcastReceiver@69d089a
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:878)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:739)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:148)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:5401)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:725)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:615)
06-22 08:35:04.370  5299  5299 E AndroidRuntime: Caused by: java.lang.IllegalArgumentException: listener already in use
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.net.nsd.NsdManager.discoverServices(NsdManager.java:559)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at org.physical_web.physicalweb.MdnsUrlDiscoverer.startScanning(MdnsUrlDiscoverer.java:76)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at org.physical_web.physicalweb.UriBeaconDiscoveryService$ScreenBroadcastReceiver.onReceive(UriBeaconDiscoveryService.java:538)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        at android.app.LoadedApk$ReceiverDispatcher$Args.run(LoadedApk.java:868)
06-22 08:35:04.370  5299  5299 E AndroidRuntime:        ... 7 more
```

**Comment by cco3** [comment]
Thanks for the report.  I have some ideas what might be wrong here.

**Comment by scottjenson** [comment]
Is this fixed? @cco3

**Comment by cco3** [comment]
Probably, I've entirely rewritten that code.
