### ISSUE TITLE
Android build error : com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)

### ISSUE THREAD

**Issue by itsyash** [google/physical-web#644]
I have cloned this project locally but not able to build it.

If I run ./gradelw ---stacktrace installDebug at the `app` level, I am getting this error :

```
Unknown source file : UNEXPECTED TOP-LEVEL EXCEPTION:
Unknown source file : com.android.dx.cf.iface.ParseException: bad class file magic (cafebabe) or version (0034.0000)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.parse0(DirectClassFile.java:472)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.parse(DirectClassFile.java:406)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.parseToInterfacesIfNecessary(DirectClassFile.java:388)
Unknown source file :   at com.android.dx.cf.direct.DirectClassFile.getMagic(DirectClassFile.java:251)
Unknown source file :   at com.android.dx.command.dexer.Main.processClass(Main.java:704)
Unknown source file :   at com.android.dx.command.dexer.Main.processFileBytes(Main.java:673)
Unknown source file :   at com.android.dx.command.dexer.Main.access$300(Main.java:83)
Unknown source file :   at com.android.dx.command.dexer.Main$1.processFileBytes(Main.java:602)
Unknown source file :   at com.android.dx.cf.direct.ClassPathOpener.processArchive(ClassPathOpener.java:284)
Unknown source file :   at com.android.dx.cf.direct.ClassPathOpener.processOne(ClassPathOpener.java:166)
Unknown source file :   at com.android.dx.cf.direct.ClassPathOpener.process(ClassPathOpener.java:144)
Unknown source file :   at com.android.dx.command.dexer.Main.processOne(Main.java:632)
Unknown source file :   at com.android.dx.command.dexer.Main.processAllFiles(Main.java:510)
Unknown source file :   at com.android.dx.command.dexer.Main.runMonoDex(Main.java:280)
Unknown source file :   at com.android.dx.command.dexer.Main.run(Main.java:246)
Unknown source file :   at com.android.dx.command.dexer.Main.main(Main.java:215)
Unknown source file :   at com.android.dx.command.Main.main(Main.java:106)
Unknown source file : ...while parsing org/physical_web/collection/BitmapRequest$RequestCallback.class
Unknown source file : 1 error; aborting
```
Why it's having problem with RequestCallback class, I haven't even touched the code after cloning.

**Comment by itsyash** [comment]
I solved it by changing the jdk from 1.8 to 1.7.
