### ISSUE TITLE
Resolve Scan returning an error

### ISSUE THREAD

**Issue by kevinahuber** [google/physical-web#654]
Two URLs: 
```
https://www.cvs.com/deals/deals.jsp
https://www.kroger.com/topic/in-store-services
```
are not working with the physical web resolve service, http://service.physical-web.org/resolve-scan, but are valid URLs. Here is my error message:
```
Traceback (most recent call last):
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 1102, in __call__
    return handler.dispatch()
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File "/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py", line 570, in dispatch
    return method(*args, **kwargs)
  File "/base/data/home/apps/s~url-caster/1.391444449619714950/handlers.py", line 80, in post
    output = helpers.BuildResponse(objects, secure_only)
  File "/base/data/home/apps/s~url-caster/1.391444449619714950/helpers.py", line 106, in BuildResponse
    logging.error('ComputeGroupId url:{0}, title:{1}, description:{2}'.format(siteInfo.url, siteInfo.title, siteInfo.description))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 86: ordinal not in range(128)
```

It looks like `\xa0` is not handled well. We could use `unicodedata.normalize()` before sending the results to prevent this and future errors. I cannot send in a fix now, but will be able to this weekend.

**Comment by scottjenson** [comment]
@kevinahuber I'm cleaning up old Issues that seem to have gone stale. Is this still an issue? If so, please reopen and we can discuss.

**Comment by kevinahuber** [comment]
@scottjenson They are still causing an issue in the current PWS- but the CVS one should have been fixed with the Group ID formation. Which version is running on `http://service.physical-web.org`?

The Kroger URL still is causing issues- I believe because of how the encoding is determined.

**Comment by scottjenson** [comment]
Can you tell me more? I just ran both through verify.physical-web.org and they worked.

**Comment by kevinahuber** [comment]
```
curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"https://www.cvs.com/deals/deals.jsp"}]}' http://service.physical-web.org/resolve-scan
<html>
  <head>
    <title>Internal Server Error</title>
    <style>
      body {
        padding: 20px;
        font-family: arial, sans-serif;
        font-size: 14px;
      }
      pre {
        background: #F2F2F2;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
    the requested operation.</p>
    <pre>Traceback (most recent call last):
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1102, in __call__
    return handler.dispatch()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 570, in dispatch
    return method(*args, **kwargs)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/handlers.py&quot;, line 78, in post
    output = helpers.BuildResponse(objects)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/helpers.py&quot;, line 101, in BuildResponse
    logging.error('ComputeGroupId url:{0}, title:{1}, description:{2}'.format(siteInfo.url, siteInfo.title, siteInfo.description))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xa0' in position 64: ordinal not in range(128)
</pre>
  </body>
</html>%      
```

That one should have been resolved with #656 , and works locally with that branch


```
curl -k -s -H "Content-Type: application/json" -d '{"objects":[{"url":"https://www.kroger.com/topic/in-store-services"}]}' http://service.physical-web.org/resolve-scan
<html>
  <head>
    <title>Internal Server Error</title>
    <style>
      body {
        padding: 20px;
        font-family: arial, sans-serif;
        font-size: 14px;
      }
      pre {
        background: #F2F2F2;
        padding: 10px;
      }
    </style>
  </head>
  <body>
    <h1>Internal Server Error</h1>
    <p>The server has either erred or is incapable of performing
    the requested operation.</p>
    <pre>Traceback (most recent call last):
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1535, in __call__
    rv = self.handle_exception(request, response, e)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1529, in __call__
    rv = self.router.dispatch(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1278, in default_dispatcher
    return route.handler_adapter(request, response)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 1102, in __call__
    return handler.dispatch()
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 572, in dispatch
    return self.handle_exception(e, self.app.debug)
  File &quot;/base/data/home/runtimes/python27/python27_lib/versions/third_party/webapp2-2.5.2/webapp2.py&quot;, line 570, in dispatch
    return method(*args, **kwargs)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/handlers.py&quot;, line 78, in post
    output = helpers.BuildResponse(objects)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/helpers.py&quot;, line 69, in BuildResponse
    siteInfo = GetSiteInfoForUrl(url, distance, force_update)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/helpers.py&quot;, line 169, in GetSiteInfoForUrl
    siteInfo = FetchAndStoreUrl(siteInfo, url, distance, force_update)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/helpers.py&quot;, line 205, in FetchAndStoreUrl
    return StoreUrl(siteInfo, url, result.content, encoding)
  File &quot;/base/data/home/apps/s~url-caster/1.392839177079585096/helpers.py&quot;, line 348, in StoreUrl
    value = htmltree.xpath(&quot;//body//*[not(*|self::script|self::style)]/text()&quot;)
  File &quot;lxml.etree.pyx&quot;, line 1444, in lxml.etree._Element.xpath (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:41805)
  File &quot;xpath.pxi&quot;, line 321, in lxml.etree.XPathElementEvaluator.__call__ (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:117918)
  File &quot;xpath.pxi&quot;, line 242, in lxml.etree._XPathEvaluatorBase._handle_result (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:117120)
  File &quot;extensions.pxi&quot;, line 546, in lxml.etree._unwrapXPathObject (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:112580)
  File &quot;extensions.pxi&quot;, line 580, in lxml.etree._createNodeSetResult (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:112953)
  File &quot;extensions.pxi&quot;, line 602, in lxml.etree._unpackNodeSetEntry (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:113129)
  File &quot;extensions.pxi&quot;, line 719, in lxml.etree._buildElementStringResult (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:114190)
  File &quot;apihelpers.pxi&quot;, line 1347, in lxml.etree.funicode (third_party/apphosting/python/lxml/v2_3_5/src/lxml/lxml.etree.c:21951)
UnicodeDecodeError: 'utf8' codec can't decode byte 0xae in position 13: invalid start byte
</pre>
  </body>
</html>% 
```

This one has not been fixed in the open source physical web service,  and I _believe_ is failing because of the execution of the logic here: https://github.com/google/physical-web/blob/master/web-service/helpers.py#L240

**Comment by scottjenson** [comment]
So is your issue with the open source PWS or the Google version?

**Comment by kevinahuber** [comment]
Open Source, I believe. The version that is on `http://service.physical-web.org`
