### ISSUE TITLE
Crash on first startup

### ISSUE THREAD

**Issue by cco3** [google/physical-web#856]
Installing a build from master, the first startup crashes for me on Android.  Second startup seems to work fine.

11-22 11:07:12.365 26121 26121 E AndroidRuntime: java.lang.NullPointerException: Attempt to invoke virtual method 'org.physical_web.collection.PwsResult org.physical_web.collection.PwPair.getPwsResult()' on a null object reference
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at org.physical_web.physicalweb.Utils$PwPairRelevanceComparator.compare(Utils.java:120)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at org.physical_web.physicalweb.Utils$PwPairRelevanceComparator.compare(Utils.java:119)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at java.util.TimSort.binarySort(TimSort.java:292)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at java.util.TimSort.sort(TimSort.java:217)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at java.util.Arrays.sort(Arrays.java:1523)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at java.util.Collections.sort(Collections.java:238)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at org.physical_web.physicalweb.NearbyBeaconsFragment.emptyGroupIdQueue(NearbyBeaconsFragment.java:392)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at org.physical_web.physicalweb.NearbyBeaconsFragment.-wrap1(NearbyBeaconsFragment.java)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at org.physical_web.physicalweb.NearbyBeaconsFragment$1.run(NearbyBeaconsFragment.java:101)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
11-22 11:07:12.365 26121 26121 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)

**Comment by cco3** [comment]
Obsolete
